### ISSUE TITLE
Feature Req: Ability to run on Linux boxes

### ISSUE THREAD

**Issue by WardsParadox** [Interfiber/pak#4]
Started exploring Pak, loving it so far. Might look to replace my munkipkg workflows with this. Is it possible to build this for Linux? Attempting to get this to build via m1 devices for linux is hitting some build issues, but I think that's an environment thing.

**Comment by Interfiber** [comment]
currently pak does not support other operating systems, other than Mac OS. This is due to it relying Mac OS specific build tools.
